from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.binding_discovery.capture_utils import mask_secret, should_block_url


KEY_PATTERNS = {
    "auth_request_found": "/cczukaoyan/rest/auth",
    "sso_auth_found": "/rest/ssoAuth",
    "act_code_bind_found": "/actCodeBind",
    "check_activation_code_found": "/checkActivationCode",
    "school_search_found": "/searchAllSchools",
    "school_by_code_found": "/getSchoolByCode",
    "cczukaoyan_user_found": "/cczukaoyan/rest/v2/user",
}


def load_records(path: Path) -> list[dict[str, Any]]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, list):
        raise ValueError("capture file must contain a JSON array")
    return [item for item in value if isinstance(item, dict)]


def analyze_capture(path: Path) -> dict[str, Any]:
    records = load_records(path)
    urls = [str(record.get("url", "")) for record in records]

    report: dict[str, Any] = {
        "file": str(path),
        "total_records": len(records),
        "free_book_requests": sum(1 for url in urls if should_block_url(url)),
        "key_urls": {},
    }

    for field, pattern in KEY_PATTERNS.items():
        matches = [url for url in urls if pattern in url]
        report[field] = bool(matches)
        report["key_urls"][field] = matches[:5]

    report["next_step"] = decide_next_step(report)
    return report


def decide_next_step(report: dict[str, Any]) -> str:
    if report["free_book_requests"]:
        return "捕获中出现 freeBook，请丢弃该文件并重新只走登录/绑定流程。"
    if report["auth_request_found"] and report["cczukaoyan_user_found"]:
        return "已看到小程序 auth 和 user 校验链路，可以继续分析 auth password 来源。"
    if report["sso_auth_found"] or report["act_code_bind_found"]:
        return "已看到 SSO/激活码绑定链路，下一步检查是否能推导小程序 auth 凭据。"
    return "关键链路不足，请确认流程是否完成登录、选学校、激活码绑定。"


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze a sanitized binding capture.")
    parser.add_argument("capture", type=Path, help="Path to capture JSON generated by capture_web.py")
    args = parser.parse_args()

    report = analyze_capture(args.capture)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
