export const PRO_PRICE_CENTS = 2000;
export const FREE_SCHOOL_ACCOUNT_LIMIT = 1;
export const PRO_SCHOOL_ACCOUNT_LIMIT = 3;
export const ADMIN_SCHOOL_ACCOUNT_LIMIT = 9999;
export const DEFAULT_INVITE_POINTS_COST = 10;
export const DEFAULT_INVITE_VALID_DAYS = 30;
export const DEFAULT_DAILY_ACTIVITY_POINTS = 1;
export const DEFAULT_REFERRAL_REWARD_POINTS = 5;
